app = "dawnchecker"
primary_region = "nrt"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services]]
  internal_port = 3000
  protocol = "tcp"
  script_checks = []

  [[services.ports]]
    port = 3000
    handlers = ["http"]
